name: "Bocchi Bot"
on:
  workflow_run:
    workflows: [init banner]
    types:
       - completed

jobs:
  Pre-run:
   runs-on: ubuntu-latest
   outputs:
     should_skip: ${{ steps.skip_check.outputs.should_skip }}
   steps:
     - id: skip_check
       uses: fkirc/skip-duplicate-actions@v3.4.0
       with:
         skip_after_successful_duplicate: 'true'
  Nijika-Chan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
          
      - name: Run
        env:
            tok_fb: ${{ secrets.TOK_FB }}
            tok_gif: ${{ secrets.TOK_GIF }}
        run: bash frame_main.sh "${tok_fb}" "${tok_gif}"
        continue-on-error: true
        
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Posted!!"
          repository: .
          file_pattern: README.md fb/* frameposter.sh frame_main.sh status/* 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
